modLoader = "javafml"
loaderVersion = "[1,)"
license = "CC-BY-NC-SA-4.0"
issueTrackerURL = "https://github.com/cgytrus/delight-map/issues"

[[mods]]
modId = "delightmap"
version = "${version}"
displayName = "Delight-(down)map"
authors = "ConfiG"
description = '''
Port of Delight-map by Enchanted_Games to older Minecraft versions.
'''
credits = "Enchanted_Games for making Delight-map."
logoFile = "assets/icon.png"
displayURL = "https://modrinth.com/mod/delight-down-map"
features = { javaVersion = "${java}" }

[[dependencies.delightmap]]
modId = "neoforge"
side = "CLIENT"

[[dependencies.delightmap]]
modId = "minecraft"
side = "CLIENT"

[[mixins]]
config = "delightmap.mixins.json"
